import type { Config } from "tailwindcss";

/**
 * Design tokens live here, not scattered through components.
 *
 * The palette encodes provenance, which is the core UX idea of the app:
 *   - `fact`   (amber)  = a number or string retrieved from a data provider
 *   - `infer`  (cyan)   = text generated by the model
 * A reader can tell at a glance whether they are looking at data or opinion.
 */
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        term: {
          bg: "#0A0C10", // terminal background
          panel: "#10141B", // card / panel surface
          raised: "#161B24", // hover + active surface
          line: "#1E2530", // hairline rules
          dim: "#5C6B7F", // de-emphasised text
          text: "#C9D4E2", // body text
          bright: "#EEF3F9", // headings
        },
        fact: "#F0A11B", // retrieved data
        infer: "#4CC9C0", // model-generated
        up: "#3FBF7F",
        down: "#F0554E",
      },
      fontFamily: {
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.04em" }],
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "none" },
        },
        "pulse-line": {
          "0%,100%": { opacity: "0.35" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        "fade-up": "fade-up 220ms ease-out both",
        "pulse-line": "pulse-line 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
